=== AbdeBMZZ/XML/nonRelational/fichier.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="application" type="applicationType">

    </xs:element>
    
    <xs:complexType name="applicationType">
        <xs:sequence>
            <xs:element name="etudiants" type="etudiantsType"></xs:element>
            <xs:element name="matieres" type="matieresType"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="matieresType">
        <xs:sequence>
            <xs:element name="matiere" type="matiereType" minOccurs="1" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="matiereType">
        <xs:all>
            <xs:element name ="nom" type="xs:string"></xs:element>
            <xs:element name="description" type="xs:string"></xs:element>
        </xs:all>
        <xs:attribute name="code" type="xs:ID"></xs:attribute>
    </xs:complexType>

    <xs:simpleType name="valeurType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"></xs:minInclusive>
            <xs:maxInclusive value="20"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="noteType">
        <xs:all>
            <xs:element name="valeur" type="valeurType"></xs:element>
        </xs:all>
        <xs:attribute name="matiereRef" type="xs:IDREF"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="notesType">
        <xs:sequence>
            <xs:element name="note" type="noteType" minOccurs="0" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="etudiantType">
        <xs:all>
            <xs:element name="nom" type="xs:string"></xs:element>
            <xs:element name="prenom" type="xs:string"></xs:element>
            <xs:element name="date_de_naissance" type="xs:date"></xs:element>
            <xs:element name="notes" type="notesType"></xs:element>
        </xs:all>
        <xs:attribute name="cne" type="cneType"></xs:attribute>
    </xs:complexType>
    
    <xs:simpleType name="cneType">
        <xs:restriction base="xs:ID">
            <xs:pattern value="[a-zA-Z0-9][0-9]{9}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="etudiantsType">
        <xs:sequence>
            <xs:element name="etudiant" type="etudiantType" minOccurs="0" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>



</xs:schema>

=== AbdeBMZZ/XML/relational/ficher.xml
<?xml version="1.1" encoding="UTF-8"?>

<etudiants xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation=
"./fichier.xsd">
    <etudiant cne="R136303724">
        <nom>boumaiza</nom>
        <prenom>abdellah</prenom>
        <date_de_naissance>2001-10-19</date_de_naissance>
        <notes>
            <note>
                <valeur>18</valeur>
                <matiere code="F1">
                    <nom>C#</nom>
                    <description>language de programmation</description>
                </matiere>
            </note>
        </notes>
    </etudiant>
    
</etudiants>

=== AbdeBMZZ/XML/nonRelational/fichier.xml
<?xml version="1.1" encoding="UTF-8"?>

<application xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation=
"./fichier.xsd">
    <etudiants>
        <etudiant cne="R136303724">
            <nom>boumaiza</nom>
            <prenom>abdellah</prenom>
            <date_de_naissance>2001-10-19</date_de_naissance>
            <notes>
                <note matiereRef="c_sharp">
                    <valeur>18</valeur>
                </note>
                <note matiereRef="Java">
                    <valeur>17.5</valeur>
                </note>
            </notes>
        </etudiant>
    </etudiants>
    <matieres>
        <matiere code = "c_sharp">
            <nom>Language C-sharp</nom>
            <description>language de programmation</description>
        </matiere>
        <matiere code = "Java">
            <nom>Language Java</nom>
            <description>language de programmation</description>
        </matiere>
    </matieres>
</application>
